DROP SCHEMA IF EXISTS School_Event;
CREATE SCHEMA IF NOT EXISTS School_Event;

USE School_Event;

CREATE TABLE SCHOOL (
	SCHOOL_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR (150) NOT NULL,
    PHONE VARCHAR (25) NOT NULL,
    STREET VARCHAR (150) NOT NULL,
    CITY VARCHAR (150) NOT NULL,
    STATE VARCHAR (150) NOT NULL
);

CREATE TABLE STUDENT (
	STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    SCHOOL_ID INT NOT NULL,
    NAME VARCHAR (150) NOT NULL,
    COURSE VARCHAR (200) NOT NULL,
    STAGE INT NOT NULL,
    FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL(SCHOOL_ID)
);

CREATE TABLE EVENT (
	EVENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    SCHOOL_ID INT NOT NULL,
    TYPE VARCHAR (20) NOT NULL,
    NAME VARCHAR (250) NOT NULL,
    SUBJECT VARCHAR (200) NOT NULL,
    AREA VARCHAR (150) NOT NULL,
    DURATION DATE NOT NULL,
    DT_START DATE NOT NULL,
    DT_END DATE NOT NULL,
    MAX_CAPACITY INT NOT NULL,
    FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL(SCHOOL_ID)
);

CREATE TABLE STUDENT_EVENT (
	EVENT_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    DT_IN DATETIME DEFAULT CURRENT_TIMESTAMP,
    DT_OUT DATETIME NOT NULL,
    STATUS BOOL NOT NULL,
    PRIMARY KEY (EVENT_ID, STUDENT_ID),
    CONSTRAINT FK_EVENT_ID FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID),
    CONSTRAINT FK_STUDENT_ID FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);